<h2><span style="font-family:Comic Sans MS; color:red; font-size: ">NumPy Exercises</span></h2>

In [20]:
import numpy as np
import pandas as pd

#### Exercise 1: Create a null vector that contains 10 elements

In [21]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Exercise 2: Create a vector of ones with 10 elements

In [22]:
ones_vector = np.ones(10)
ones_vector

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise 3: With the linspace function of Numpy and create an array with 10 elements

In [23]:
linspace_vector = np.linspace(1,10,10)
linspace_vector

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### Exercise 4: Create arrays using random numbers functions rand, randn and randint

In [24]:
# rand: random numbers between 0 and 1
rand_vector = np.random.rand(10)
'rand: ', rand_vector

('rand: ',
 array([0.69275017, 0.31964476, 0.14588218, 0.18875298, 0.90782571,
        0.69862338, 0.81127311, 0.18736252, 0.21724152, 0.06967685]))

In [25]:
# randn: random numbers with normal distribution which have mean of 0 and standard deviation of 1
randn_vector = np.random.randn(5,5)
'randn: ', randn_vector

('randn: ',
 array([[ 1.21572640e-02, -7.43296591e-02,  5.43659694e-01,
          1.24262868e+00, -1.13339705e-01],
        [-1.40047978e+00,  2.12584466e+00,  2.50688167e+00,
          5.42161764e-01,  1.05793835e+00],
        [ 5.64009614e-01,  1.19251013e-01, -9.95723867e-01,
          6.47177330e-01, -2.37761339e-01],
        [ 9.98542410e-01, -1.09227759e-03, -1.12422854e-01,
          6.54270800e-01,  1.35364136e+00],
        [ 1.48673448e+00,  1.29035393e+00, -2.98451614e+00,
         -1.13388988e-01, -2.81806283e-01]]))

In [26]:
# randint: random integers between 0 and 10
randint_vector = np.random.randint(1,10,size=(2,5))
'randint: ', randint_vector

('randint: ',
 array([[4, 3, 3, 3, 6],
        [5, 6, 5, 1, 8]]))

#### Exercise 5: Create a 5x5 identity matrix

In [27]:
identity_matrix = np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Exercise 6: Create a 3x2 random number matrix and calculate the minimum and maximum value

In [28]:
random_matrix = np.random.rand(3,2)
random_matrix

array([[0.90390931, 0.55853662],
       [0.63629955, 0.48924271],
       [0.49942156, 0.90706496]])

In [29]:
'Minimum value: ', np.min(random_matrix)

('Minimum value: ', 0.4892427100470118)

In [30]:
'Maximum value: ', np.max(random_matrix)

('Maximum value: ', 0.9070649635667686)

#### Exercise 7: Create a vector of 30 elements that are random numbers and calculate the mean

In [31]:
random_vector = np.random.randint(5,13,size=30)
print(random_vector)

'Mean value: ', np.mean(random_vector)

[ 6  9  8 11  8 12 12 10  9  6  5  9 11 11  5  9  8 12 11  8  9 11  6 11
  9 10  8  5 11  7]


('Mean value: ', 8.9)

#### Exercise 8: Convert the list [1, 2, 3] and the tuple (1, 2, 3) to arrays

In [32]:
list_example = [1,2,3]
tuple_example = (1,2,3)
'list_example to array: ', np.array(list_example)

('list_example to array: ', array([1, 2, 3]))

In [33]:
'tuple_example to array: ', np.array(tuple_example)

('tuple_example to array: ', array([1, 2, 3]))

#### Exercise 09: Invert the vector of the previous exercise (8)

In [34]:
'invert list_example: ', np.array(list_example)[::-1]

('invert list_example: ', array([3, 2, 1]))

In [35]:
'now invert list_example using flip()', np.flip(list_example)

('now invert list_example using flip()', array([3, 2, 1]))

#### Exercise 10: Change the size of a random array of dimensions 5x12 into 12x5

In [36]:
random_matrix2 = np.random.rand(5,12)
print(random_matrix2)

'Transponse: ', random_matrix2.T
# can also be np.transpose(random_matrix2)  or random_matrix.reshape(12,5)

[[0.48745053 0.37163516 0.19830044 0.55092977 0.54910376 0.10730915
  0.20998919 0.55983831 0.81044107 0.53595752 0.98887587 0.16135871]
 [0.02898454 0.58759257 0.19938749 0.39447336 0.23162641 0.40286231
  0.02377386 0.39312764 0.85507793 0.2533901  0.71152877 0.37231372]
 [0.7319106  0.39386065 0.35744602 0.17348317 0.01341442 0.44876049
  0.93183315 0.2639563  0.63345474 0.2964029  0.04618052 0.34567339]
 [0.19625065 0.55103641 0.8316465  0.22263772 0.32596919 0.17459069
  0.58776654 0.54370009 0.55000016 0.78585086 0.43624521 0.12971949]
 [0.03320843 0.82561407 0.09184293 0.84904965 0.32612294 0.41506049
  0.21694589 0.61399892 0.42085679 0.70012356 0.43420724 0.25610117]]


('Transponse: ',
 array([[0.48745053, 0.02898454, 0.7319106 , 0.19625065, 0.03320843],
        [0.37163516, 0.58759257, 0.39386065, 0.55103641, 0.82561407],
        [0.19830044, 0.19938749, 0.35744602, 0.8316465 , 0.09184293],
        [0.55092977, 0.39447336, 0.17348317, 0.22263772, 0.84904965],
        [0.54910376, 0.23162641, 0.01341442, 0.32596919, 0.32612294],
        [0.10730915, 0.40286231, 0.44876049, 0.17459069, 0.41506049],
        [0.20998919, 0.02377386, 0.93183315, 0.58776654, 0.21694589],
        [0.55983831, 0.39312764, 0.2639563 , 0.54370009, 0.61399892],
        [0.81044107, 0.85507793, 0.63345474, 0.55000016, 0.42085679],
        [0.53595752, 0.2533901 , 0.2964029 , 0.78585086, 0.70012356],
        [0.98887587, 0.71152877, 0.04618052, 0.43624521, 0.43420724],
        [0.16135871, 0.37231372, 0.34567339, 0.12971949, 0.25610117]]))

#### Exercise 11: Convert the list [1, 2, 0, 0, 0, 4, 0] into an array and get the index of the non-zero elements

In [37]:
my_list = [1, 2, 0, 0, 0, 4, 0]
print('List: ', my_list)

'Get index of non-zero elements: ', np.nonzero(my_list)

List:  [1, 2, 0, 0, 0, 4, 0]


('Get index of non-zero elements: ', (array([0, 1, 5], dtype=int64),))

#### Exercise 12: Convert the list [0, 5, -1, 3, 15] into an array, multiply its values by -2 and obtain the even elements


In [38]:
my_list = [0, 5, -1, 3, 15]

arr = np.array(my_list)
print(arr)
arr = arr * -2
print('Multiply array by -2: ', arr)
even_numbers = arr[arr % 2 == 0]
print('Even numbers of array: ', even_numbers)

[ 0  5 -1  3 15]
Multiply array by -2:  [  0 -10   2  -6 -30]
Even numbers of array:  [  0 -10   2  -6 -30]


#### Exercise 13: Create a random vector of 10 elements and order it from smallest to largest

In [41]:
random_vector = np.random.randint(1,100,size=10)
print('Random vector: ', random_vector)
np.sort(random_vector)

Random vector:  [90 19 93 48 89 79 92 16 61 27]


array([16, 19, 27, 48, 61, 79, 89, 90, 92, 93])

#### Exercise 14: Generate two random vectors of 8 elements and apply the operations of addition, subtraction and multiplication between them

In [48]:
v1 = np.random.randint(1,100,size=8)
v2 = np.random.randint(1,100,size=8)
print(f"Random vector 1 = {v1}\nRandom vector 2 = {v2}")

v_sum = v1 + v2
v_sub = v1 - v2
v_mult = v1 * v2

print(f"Sum = {v_sum}\nSubstraction = {v_sub}\nMultiplication = {v_mult}")

Random vector 1 = [59 69 61 66 39 98 73 70]
Random vector 2 = [97 53 24 35 37 44 31 98]
Sum = [156 122  85 101  76 142 104 168]
Substraction = [-38  16  37  31   2  54  42 -28]
Multiplication = [5723 3657 1464 2310 1443 4312 2263 6860]


#### Exercise 15: Convert the list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] into an array and transform it into a matrix with rows of 3 columns

In [53]:
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
print('my_list to array: ', np.array(my_list))
print('my_list to matrix 3x3: ', np.array(my_list).reshape(3,4))

my_list to array:  [ 1  2  3  4  5  6  7  8  9 10 11 12]
my_list to matrix 3x3:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
