<h2><span style="font-family:Comic Sans MS; color:red; font-size: ">NumPy</span></h2>

In [1]:
import numpy as np
import pandas as pd

#### Arrays
A Numpy array is a data structure that allows you to store a collection of elements, usually numbers, in one or more dimensions.
A one-dimensional (1D) array in Numpy is a data structure that contains a sequence of elements in a single dimension. It is similar to a list in Python:

In [8]:
# create 1D array with numbers 1-10
my_array = np.arange(1,11)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# access the third element in the array
my_array[2]

3

In [10]:
# access the last element in the array
my_array[-1]

10

In [12]:
# change the value of the second element to 20
my_array[1] = 20
my_array

array([ 1, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# add 10 to all elements in the array
my_array = my_array + 10
my_array

array([11, 30, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
# calculate the sum of all elements in the array
np.sum(my_array)  # or sum_all = np.sum(my_array)

173

A multidimensional or n-dimensional array in Numpy is a data structure that organizes elements in multiple dimensions (axes). These arrays allow you to represent more complex data structures, such as matrices (2D array, 2 axes), tensors (3D array, 3 axes) and higher dimensional structures.

In [18]:
# create 2D array with numbers 1-9
my_array2 = np.arange(1,10).reshape(3,3)
my_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# create 3D array with numbers 1-8
my_array3 = np.arange(1,9).reshape(2,2,2)
my_array3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### Functions
Numpy provides a large number of predefined functions that can be applied directly to the data structures seen above or to Python's own data structures (lists, arrays, etc.). 

In [20]:
# create an array for this section
my_array_example = np.arange(1,6)
my_array_example

array([1, 2, 3, 4, 5])

In [22]:
# add 10 to all elements in the array
'Sum: ', np.add(my_array_example, 10)

('Sum: ', array([11, 12, 13, 14, 15]))

In [23]:
# multiply all elements in the array by 2
'Multiply by 2: ', np.multiply(my_array_example, 2)

('Multiply by 2: ', array([ 2,  4,  6,  8, 10]))

In [24]:
# Logarithmic operations
# Natural logarithm of all elements in the array
'Natural logarithm: ', np.log(my_array_example)

('Natural logarithm: ',
 array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791]))

In [25]:
# exponential of all elements in the array
'Exponential: ', np.exp(my_array_example)

('Exponential: ',
 array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ]))

In [26]:
# Statistical Functions
# Mean of all elements in the array
'Mean: ', np.mean(my_array_example)

('Mean: ', 3.0)

In [27]:
# median of all elements in the array
'Median: ', np.median(my_array_example)

('Median: ', 3.0)

In [28]:
# standard deviation of all elements in the array
'Standard deviation: ', np.std(my_array_example)

('Standard deviation: ', 1.4142135623730951)

In [29]:
# variance of all elements in the array
'Variance: ', np.var(my_array_example)

('Variance: ', 2.0)

In [30]:
# maximum value of all elements in the array
'Maximum value: ', np.max(my_array_example)

('Maximum value: ', 5)

In [31]:
# maximum index of all elements in the array
'Minimum value: ', np.argmax(my_array_example)

('Minimum value: ', 4)

In [32]:
# minimum value of all elements in the array
'Minimum value: ', np.min(my_array_example)

('Minimum value: ', 1)

In [33]:
# minimum index of all elements in the array
'Minimum index: ', np.argmin(my_array_example)

('Minimum index: ', 0)

In [34]:
# sum of all elements in the array
'Sum: ', np.sum(my_array_example)

('Sum: ', 15)

In [36]:
# Rouding Functions
# create decimal random array with numbers 1-5
my_array_example2 = np.array([1.23, 2.47, 3.56, 4.89])
my_array_example2

array([1.23, 2.47, 3.56, 4.89])

In [37]:
# round all elements in the array
'Rounding: ', np.round(my_array_example2)

('Rounding: ', array([1., 2., 4., 5.]))

In [38]:
# minor integer (floor) of all elements in the array
'Minor integer: ', np.floor(my_array_example2)

('Minor integer: ', array([1., 2., 3., 4.]))

In [39]:
# major integer (ceil) of all elements in the array
'Major integer: ', np.ceil(my_array_example2)

('Major integer: ', array([2., 3., 4., 5.]))